name: Deploy UI & API to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH  # Ensure Fly.io is in PATH

      - name: Deploy API to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly deploy --config fly.toml

  deploy-ui:
    runs-on: ubuntu-latest
    needs: deploy-api # Ensures UI deploys only after API is successfully deployed
    defaults:
      run:
        working-directory: ui
    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH  # Ensure Fly.io is in PATH

      - name: Deploy UI to Fly.io
        # env:
        #   FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        #   NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          fly deploy --config fly.toml
